<a href="https://colab.research.google.com/github/quochuy1204/Project-3/blob/main/Project3_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets

Bước tiếp theo, chúng ta sẽ load dữ liệu và hiện thị ra 1 vài dữ liệu mẫu để check.


In [3]:
iris = datasets.load_iris();
iris_X = iris.data;
iris_Y = iris.target;
print("Number of classes: %d" %len(np.unique(iris_Y)));
print("Number of data points: %d" %len(iris_Y));

X0 = iris_X[iris_Y == 0,:]; #Lấy ra tất cả data được gán nhãn là 0
print("\nSamples from class 0:\n" , X0[:5,:]); #In ra 5 ví dụ đầu tiên trong tập data X0

X1 = iris_X[iris_Y == 1,:]; #Lấy ra tất cả data được gán nhãn là 1
print("\nSamples from class 1:\n" , X1[:5 ,:]); #In ra 5 ví dụ đầu tiên trong tập data X1

X2 = iris_X[iris_Y == 2,:]; #Lấy ra tất cả data được gán nhãn là 2
print("\nSamples from class 2:\n" , X2[:5,:]); #In ra 5 ví dụ đầu tiên trong tập data X2

Number of classes: 3
Number of data points: 150

Samples from class 0:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Samples from class 1:
 [[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]]

Samples from class 2:
 [[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]]


Bước tiếp theo, chúng ta sẽ tách tập data set thành 1 tập data training và data test.


In [5]:
from sklearn.model_selection import train_test_split; #Scikit-learn có hàm giúp chúng ta chia tập data set
X_train, X_test , Y_train , Y_test = train_test_split(iris_X , iris_Y , test_size = 50); #Data set sẽ được chia thành 50 data cho tập test và data còn lại là tập training
print("Training size: %d" %len(Y_train)); #In ra số data trong tập train
print("Test size: %d" %len(Y_test)); #In ra số data trong tập test

Training size: 100
Test size: 50


Trước tiên, mình sẽ xét trường hợp đơn giản nhất với K = 1, tức là với mỗi điểm data test, ta chỉ xét 1 điểm data training gần nhất và lấy label của điểm đó để dự đoán label cho điểm test này.


In [6]:
clf = neighbors.KNeighborsClassifier(n_neighbors = 1 , p = 2); #Gọi hàm thực thi thuật toán KNN classifier với k = 1 và p = 2 tức là khoảng cách từ điểm data test tới data train được tính theo norm 2
clf.fit(X_train , Y_train);
Y_pred = clf.predict(X_test);

print("Print results for 20 test data points: ");
print("Predicted labels:", Y_pred[20:40]);
print("Ground truth    :" , Y_test[20:40]);

Print results for 20 test data points: 
Predicted labels: [1 2 2 1 2 1 2 1 0 2 0 1 1 0 2 0 1 2 0 1]
Ground truth    : [1 2 2 1 2 1 2 1 0 1 0 1 1 0 2 0 2 2 0 1]


Kết quả cho thấy, label dự đoán gần như chính xác hoàn toàn so với label thật của test data, chỉ có duy nhất 2 điểm trong số 20 điểm được hiện thị có kết quả sai lệch. Ground truth ở đây chính là nhãn/label/output thực sứ của các điểm trong test data.
Bước tiếp theo, chúng ta sẽ đánh giá độ chính xác của thuật toán KNN classifier.

In [7]:
from sklearn.metrics import accuracy_score;
print("Accuracy of 1NN: %.2f %%" %(100*accuracy_score(Y_test , Y_pred)));

Accuracy of 1NN: 96.00 %


Như chúng ta thấy, kết quả cho ra là 98%, khá cao so với số K = 1. Tuy nhiên để nâng độ chính xác của thuật toán KNN trong bài toán classification chúng ta sẽ tiến tới bước tiếp theo đó là thử tăng số K lên.

In [14]:
clf = neighbors.KNeighborsClassifier(n_neighbors = 10 , p = 2 );
clf.fit(X_train , Y_train);
Y_pred = clf.predict(X_test);

print("Accuracy of 10NN with major voting: %.2f %%" %(100*accuracy_score(Y_test , Y_pred)));

Accuracy of 10NN with major voting: 98.00 %


In [12]:
from sklearn.metrics import recall_score;
print("Recall of 10NN: %.2f %%" %(100*recall_score(Y_test , Y_pred , average = 'micro')));

Recall of 10NN use Marco: 98.00 %


In [13]:
from sklearn.metrics import precision_score;
print("Precision score of 10NN: %.2f %%" %(100*precision_score(Y_test , Y_pred , average = 'micro')));


Precision score of 10NN: 98.00 %
